-- ============================================================================
-- 20. HOSPITALS CATALOG
-- ----------------------------------------------------------------------------
-- Autocomplete source for the Hospital/Clinic inputs on /quick-help (urgent)
-- and /booking (planned). Scraped from Google Maps across the Noida region,
-- deduped + cleaned. `label` is the full "Name, Area" shown in the datalist.
-- Publicly readable (no PII); refresh by re-running the my-crawler scraper and
-- re-seeding. Idempotent: safe to run repeatedly.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.hospitals (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    label       TEXT NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read hospitals" ON public.hospitals;
CREATE POLICY "Anyone can read hospitals"
    ON public.hospitals FOR SELECT TO anon, authenticated
    USING (true);

INSERT INTO public.hospitals (label) VALUES
  ('AAROGYA INDIA WELLNESS HOSPITAL, Plot no GH-14A'),
  ('AAV Polyclinic, Greater Noida'),
  ('AMC Hospital, Haldoni More Road'),
  ('ANS SUPERSPECIALITY HOSPITAL, NH22, Swarn Nagari'),
  ('AROGAYA HOSPITAL, Arogaya Hospital, MILAK LACHI, MAIN ROAD'),
  ('ASG Eye Hospital, Noida Sector 18'),
  ('Aashirwad Multispeciality Clinic, Noida West'),
  ('Aastha Clinic, Noida'),
  ('Abhay Clinic, Noida Sector 62'),
  ('Advance Hair Clinic : Hair Patch & Wig in Noida, Noida'),
  ('Advance Poly Clinic, Noida West'),
  ('Agilus Diagnostics, Noida Sector 18'),
  ('Agrawal clinic-Dr.Amit Agrawal, Noida West'),
  ('Ahana Health Care, Gali No.-2, near mother dairy, Sharma market'),
  ('Align & Smile Dental Care- Multi-speciality Dental Clinic, Noida Sector 18'),
  ('Amritaya Clinic, 1st Floor, JOP Plaza, P2, Market'),
  ('Anmol Clinic, Noida West'),
  ('Apex Multispeciality Hospital, Noida'),
  ('Apna Health Clinic, Noida'),
  ('Apollo 24, 4th Floor, Som Datt Tower, Plot No.K-2'),
  ('Apollo Clinic, Plot No-218, Greater Noida W Rd'),
  ('Apollo Cradle & Children and Apollo Spectra Hospitals, Pocket 7, NSG Chowk, NH-27, near IFS Villas'),
  ('Apollo Fertility, Noida Sector 18'),
  ('Apollo Hospital Accomodation, Noida'),
  ('Apollo Hospitals Emergency Helpline Centre, Noida'),
  ('Apollo Hospitals Noida, Noida'),
  ('Apollo hospital gol chakkar, Noida'),
  ('Arcane Skin & Hair Clinic, Noida'),
  ('Arihant Diagnostics / Dr Neha''s Ultrasound (Female Radiologist in Gaur City 1 and 2, Noida Extension, Greater Noida West), Noida West'),
  ('Assure Health clinic & Digital X-RAY, Noida West'),
  ('Astha Hospital, Noida'),
  ('Aurelle d''luxe, Second floor, P block, above iCrest Apple Store'),
  ('Axis Physiotherapy & Chiropractor Advanced Ortho Neuro Clinic in Greater Noida West, Greater Noida West'),
  ('Ayu Health Hospitals, Noida'),
  ('BLESSINGS POLYCLINIC, Noida West'),
  ('Baba Mohan Ram Hospital, Noida West'),
  ('Balaji Clinic, Noida West'),
  ('Batra Hospital & Medical Research Centre, Noida'),
  ('Bengali Clinic, 320, Industrial Area Sector 62 Noida, NCR'),
  ('Berkowits Hair & Skin Clinic, Main J-1, Maharaja Agrasen Marg, opposite The great india place mall'),
  ('Best General Surgeon in Sector 34 Noida, Noida'),
  ('Best Hearing Clinics, Noida Sector 18'),
  ('Bhardwaj Hospital, Noida'),
  ('Biprashi Hospital, Noida'),
  ('Blood Bank Kailash Hospital, Noida'),
  ('Blossom Women''s Clinic, Noida Sector 137'),
  ('Bud IVF & Fertility Center- Best IVF centre and clinic in noida, Noida Sector 18'),
  ('CAREPLUS MULTISPECIALITY CLINIC, D-357, Greater Noida W Rd'),
  ('CHAUDHARY HOSPITAL, 49, Sector 76 Rd'),
  ('CLINIQ MEDICAID Noida, Noida'),
  ('Calcutta Clinic, Noida Sector 62'),
  ('Care Dental & Health Clinic, 101, First Floor, Singhal Tower - Glass Building, near Labour Chowk'),
  ('Care First Polyclinic, Greater Noida'),
  ('Career Clinic Study Abroad, Noida Sector 62'),
  ('Chandra Hospital, Noida'),
  ('Chaturbhuj Hospital, a-5, Sector 57 Rd'),
  ('Chauhan Ayurveda, Noida'),
  ('Chetram Paisal Nursing Home, Noida'),
  ('Children Clinic, 116/3, Saraswati Vihar, Khoda Colony Sector 62 A, Noida, Saraswathi Vihar, Khora Colony, Sector 62A, Ghaziabad, Meerut Division Delhi'),
  ('City Medicare, 102, Tara Enclave, near Sector 62'),
  ('Clair Skin Clinic, Noida Extension'),
  ('Clinic on rent in Noida- Nexgen multi-speciality clinic, Noida'),
  ('Clinic, Shop.No-5,First Floor, Sanjay Market, Atta'),
  ('Cloudnine Hospital, Noida'),
  ('Clove Dental Clinic in Sector 62, Noida, Noida Sector 62'),
  ('Coddle Wellness, Noida Sector 18'),
  ('Curewell Dental Clinic, Noida Sector 18'),
  ('DHI™ India, Noida Sector 18'),
  ('DM Homeopathic clinic, Noida Sector 137'),
  ('DOC 24 Clinic: Dr Raman Kumar, Ground Floor 02, Galleria Market, 49, Gaur City'),
  ('DR AHUJA '' S TOOTH CARE, B2/178 BASEMENT, near B2 BLOCK MARKET'),
  ('DR LAL PATHLABS LTD FPSC ECOCITY, SEC-137 ,NOIDA, Noida Sector 137'),
  ('DR S K THAKUR, Best physician/MD medicine in noida extension. Specialist in diabetes, BP, thyroid, infections, chest ,heart, SUPERTECH MARKET, SUPERTECH ECO VILLAGE-1, 17 A'),
  ('DT Aesthetics, Noida'),
  ('Demo Hospital, Noida Sector 18'),
  ('Department of Urology, Noida'),
  ('Dev Clinic, Main Road, opposite Shiv Mandir'),
  ('Devansh Clinic, Noida West'),
  ('Dhanwantri Clinic, Shop No - 3, Plot no-287'),
  ('Diabetes Thyroid Hormone Centre Sect -18 Noida, adjacent Metro Station Noida Sector 18'),
  ('Dipakshi Hospital – Best Multispeciality Hospital in Noida, Udhayan Marg'),
  ('District combined Hospital, Gautam Budhnagar, Noida'),
  ('Divine Healthcare, First Floor, Commercial Complex, Ace Divino, Greater Noida W Rd'),
  ('Divine Hospital, Noida'),
  ('Doctor Care 24, Noida Sector 62'),
  ('Doctor In Sector 62 Noida, Dr.Promila Chauhan, Religare Pharmacy Tot mall Sector 62'),
  ('Doctor’s Clinic & Lab, Shop No. 1 & 2, Deewan Plaza, Greater Noida W Rd, near Ace Divino'),
  ('Dr Abhishek Gulia, Noida'),
  ('Dr Amandeep Singh, LG-23, La Galleria Market, Greater Noida W Rd'),
  ('Dr Anil Thakwani/VEJOVIS Superspeciality Clinic, Noida'),
  ('Dr Ankita Pal, F block, Sector 02, F-117'),
  ('Dr Anurag Aggarwal, Noida Sector 62'),
  ('Dr Arpit Varshney, UGF-08, DG MEDIGYN Clinics, SAVIOUR GREENARCH MARKET opposite Cherry County Street Near Ek Murti Techzone 4, Noida, Extension'),
  ('Dr Ayushi''s Physiotherapy clinic, Noida Sector 137'),
  ('Dr Batra’s Homeopathy, Hair & Skin Clinic, Noida'),
  ('Dr Bhimrao Ambedkar Multispeciality Hospital, PATIENT ROOM, Maharaja Agrasen Marg, near Delhi Public School'),
  ('Dr Diksha Dental and Aesthetic Clinic, Noida Sector 62'),
  ('Dr Jasbir Physiotherapy Clinic, Noida Sector 137'),
  ('Dr Lal PathLabs, Noida Sector 62'),
  ('Dr Love Kumar Jha (General Physician & Pulmonology Care), 1st Floor, Commercial Complex, STELLAR JEEVAN, Shop CH 109, Greater Noida W Rd'),
  ('Dr Meenakshi maurya/Women health clinic, shop no LGF 45, biz park, WOMEN HEALTH CLINIC, Greater Noida W Rd'),
  ('Dr Mitra''s Clinic, Ground Floor, Central Market, 5, AWHO Rd'),
  ('Dr Padam Singh Gautam, Noida Sector 62'),
  ('Dr Pankaj Pal, 117,F block, Dr Pankaj ,cabin'),
  ('Dr Puneet Bhardwaj, Noida Sector 137'),
  ('Dr R.K.RANA, Vishal mega Mart, Shop no 406 Deepak vihar labour chowk Khora colony Noida sector 58'),
  ('Dr Rana General Hospital, 1, 105, Azad Vihar, Khora Colony, Sector 62A, Ghaziabad Delhi, RC-556'),
  ('Dr Rashmi Rajan Obstetrician and gynaecologist/ Associate consultant at yatharth hospital,sector 110,Noida, Noida Sector 137'),
  ('Dr Ruchika Prakash, MBBS, MD Medicine (General Physician), Noida Sector 137'),
  ('Dr Savyasachi Saxena, Ent Specialist, Ent Surgeon, Sinusitis/Thyroid Treatment, Best Ent Doctor, Ent Specialist in Noida, Fortis Hospital, B-22, Sector-62, Noida'),
  ('Dr Utkarsh Gupta, GF-08, High Street Market, Gaur Saundaryam, Greater Noida W Rd'),
  ('Dr Vasun Batra''s ENT Centre, FIRST FLOOR, Mahagun Mywoods Mart, Shop no. 141, Greater Noida W Rd'),
  ('Dr Virad Kumar, Noida'),
  ('Dr Vishrut Singh- Best pediatrician/ child specialist in Noida, Noida Sector 137'),
  ('Dr sheikh, Noida Sector 18'),
  ('Dr. Anju Verma Memorial Clinic, Greater Noida'),
  ('Dr. Anshu Singla Physiotherapy Clinic, 14, Sector 62, Ghaziabad Delhi'),
  ('Dr. Astha Gupta- Best Fertility Doctor Noida, Noida'),
  ('Dr. Azad Sexologist, 3rd floor, Bhawani Market, Delhi Metro Blue Line'),
  ('Dr. B. K. Roy, Noida Sector 18'),
  ('Dr. Bakshi''s Bakson''s Homoeopathy Noida, Noida Sector 18'),
  ('Dr. Chaurasiya Clinic Sexologist in Noida, Deepak Vihar Bishanpura Road Khoda Colony Sector 62, Noida J953+V4W Bishanpura Road, Sector 57 Rd'),
  ('Dr. Deepika''s Homeopathy, Noida Sector 62'),
  ('Dr. Deepti Rana, Noida Sector 18'),
  ('Dr. Haror''s Wellness, Second Floor, Block-P, P-12A'),
  ('Dr. Ila Kathuria, Ocean Complex, Noida Sector 18'),
  ('Dr. J. K. Gupta ENT Clinic Sec-137 Noida, Noida Sector 137'),
  ('Dr. Jetavya Kushwaha, Greater Noida West'),
  ('Dr. K.K Tripathi / Dr Riti Srivastava (Shri Krishna Clinic), Greater Noida'),
  ('Dr. Manali, Noida West'),
  ('Dr. Manu Madan (DM, AIIMS), Noida'),
  ('Dr. Monica Malik, Noida'),
  ('Dr. Narendra Gupta, Noida'),
  ('Dr. Naveen Prakash Verma Clinic,Sec110, Noida Extension'),
  ('Dr. Neelu Agrawal, Second floor, Galaxy Diamond Plaza, Shop no, SB 203, near Gaur chowk'),
  ('Dr. Om Prakash Kumar, Noida Sector 18'),
  ('Dr. R.K. Avasthi Medical Clinic (Top General Physician in Noida), Noida Sector 137'),
  ('Dr. R.N. Singh Hospital, Noida'),
  ('Dr. Rahul Gupta, Noida'),
  ('Dr. Renu Roy, Noida Sector 18'),
  ('Dr. Richa Thukral, Noida'),
  ('Dr. Ritika Gaur, Noida Sector 137'),
  ('Dr. Ritu Prabhakar Homoeopathic Clinic, Noida Sector 137'),
  ('Dr. Rohit Khandelwal, Noida'),
  ('Dr. Ruchi Dubey, Shop No. F-07, First Floor, Sky Plaza, Sector 16B Rd'),
  ('Dr. Saurabh Kapoor best spine surgeon in Delhi, Noida'),
  ('Dr. Shikha Khare MD DERMATOLOGIST (Trimed Multi speciality clinic), Trimed Multi speciality clinic, Greater Noida W Rd'),
  ('Dr. Singh Clinic, Babu Complex, Captain Vijyant Thapar Marg'),
  ('Dr. Sneha Bakshi (MBBS) General Physician Visiting consultant Nu Med hospital, Greater Noida West'),
  ('Dr. Swati Chauhan Clinic, Noida'),
  ('Dr. Utpal Kumar Singh, M.D. Physician, PGDCC , AFIH, Upper Ground Floor, Shop no.9, NIRALA ESTATE, Market, Greater Noida W Rd'),
  ('Dr. Vishal Gupta, Best Diabetologist and General Physician in Gaur City 1 (City Plaza) and Guar City 2 (Mahagun mart), 1st floor, Mahagun Mart, 208 2nd floor City plaza extension, Gaur City 1, Noida, Uttar Pradesh. 149'),
  ('Dr.Anuja Rajoriya, Greater Noida West'),
  ('Dr.Rajat Bajaj, Noida Sector 62'),
  ('Dr.Shweta Pagare, Noida Sector 137'),
  ('ESIC Model Hospital, H8RX+69R, A-3, Tulsi Marg'),
  ('Emergency Hospital in Noida Sector 128, Noida'),
  ('Face look hair fixing Clinic, 2nd floor, chaudhry Raampal Awana complex, metro station, next to Chakki Wali Gali, near Noida Sector 18'),
  ('FaceStudio Dental Clinics, Noida Sector 137'),
  ('Family Clinic & Physiotherapy Centre, Shop no 1, Gajan Market'),
  ('Family Clinic, Noida West'),
  ('Family Health Clinic, Noida'),
  ('Fatima Health Clinic, Noida West'),
  ('Felix Hospital, Noida'),
  ('Fever Clinic, Noida'),
  ('Fine Dr hair transplant clinic best hair transplant in noida up, Noida'),
  ('FlexifyMe Advanced Physiotherapy Clinic in Sector 18, Noida, Noida Sector 18'),
  ('Fortis Healthworld, GF-31/41, Pearl Plaza, Block K-24,'),
  ('Fortis Hospital Greater Noida, Noida'),
  ('Fortis Hospital Noida, Noida'),
  ('GAYATRI CLINIC, Noida'),
  ('GET LOOK Hair Fixing Clinic, Noida Sector 18'),
  ('GIMS Hospital Greater Noida UP, Greater Noida'),
  ('Galaxy Healthcare, shop no. 5, Trinity primus, noida extension'),
  ('Gautam Ayurveda-Best Sexologist in Noida, India, Noida Sector 18'),
  ('Global Clinic Noida, Noida'),
  ('Good Hope Clinic, Noida West'),
  ('Government District Combined Hospital, Noida'),
  ('Government child specially hospital, Noida'),
  ('Green City Hospital, NH-17, Delta 1 Block C Rd'),
  ('Gupta hospital and maternity center, Noida Sector 62'),
  ('Gurukripa Clinic, Greater Noida West'),
  ('HARMONY CLINIC MULTISPECIALITY CLINIC, LG 26 LA RESIDENTIA MARKET, Greater Noida W Rd'),
  ('HEALTHCARE24 CLINIC, Durga Vihar, road, behind AMRAPALI SAPPHIRE, near bhola bikaner sweets'),
  ('HEALTHY CHOICE FAMILY CLINIC, PRADHAN MARKET ROZA YAKUBPUR Shop no. 6 basement Near Urjatech golchakkar, near AJNARA LE GARDEN'),
  ('Hariom Homeo — Homeopathy Clinic Noida, Noida Sector 18'),
  ('Harsh Clinic, Noida West'),
  ('Health And Wellness Clinic, H8CG+C8G NCR Region, Captain Vijyant Thapar Marg'),
  ('Health Clinic, Block-A5, 415, Pwana Vihar, Ghaziabad Delhi'),
  ('Health First Clinic, Greater Noida West'),
  ('Heritage Hospitals Noida, Heritage Hospitals Limited, Plot No - 1A'),
  ('Homeo Care Clinic, Tower E4 Flat No 1904 Supertech Eco Village 1, Sector 1 Noida, West'),
  ('Homoeo Amigo : Best Homeopathy clinic in Noida 18, Noida Sector 18'),
  ('Ideal Clinic, Greater Noida'),
  ('InSmile Dental Clinic – Advanced Dental Care, Noida, Shop number 23, Tot Mall market'),
  ('IndoGulf Hospital & Diagnostics, B-498 A, Tulsi Marg'),
  ('Internal Medicine Hospital in Noida, Noida'),
  ('Ivory hospital, NH-25, Pocket, Greater Noida'),
  ('J. R. Chaudhary Hospital Pvt. Ltd., Noida'),
  ('J.M.D CLINIC, Greater Noida'),
  ('JYRAJ CLINIC(Multispecialty), Noida Sector 137'),
  ('Jeevan Clinic, Noida Sector 62'),
  ('Jeevan Hospital, Noida'),
  ('Kabir Clinic, Noida Extension'),
  ('Kailash Health Village, Noida Sector 62'),
  ('Kailash Hospital & Heart Institute, H-33, Shaheed Arjun Sardana Marg'),
  ('Kailash Hospital & Neuro Institute, Noida'),
  ('Kailash Hospital, Greater Noida, Plot No 23, near Pari Chowk'),
  ('Kalawati Shankar Clinic, Noida Sector 18'),
  ('Kamla Health Clinic, Greater Noida'),
  ('Kashvi Multispeciality Hospital, Noida'),
  ('Kaya Clinic, Noida'),
  ('Kirti Clinic, Noida West'),
  ('Kumar Hospital – Best Hospital in Greater Noida, Noida'),
  ('Kyno Health, Greater Noida'),
  ('LIFELINE MEDICARE CLINIC, Noida West'),
  ('LYF Hospital, 4th Avenue, Greater Noida W Rd, opposite City Plaza'),
  ('Life Care Clinic, Greater Noida West'),
  ('Life Care Hospital, E-1, Badal Marg'),
  ('Looks & Care Wellness, Noida Sector 18'),
  ('M S Health Care Center, Shop No 6, NCR Region, Ransher Market'),
  ('M&D CLINIC, Noida Sector 18'),
  ('MANAS HOSPITAL FOUNDATION (surgical & multispeciality Hospital), Greater Noida'),
  ('MASSH, Noida'),
  ('MAXcare Multispeciality Clinic, Greater Noida West'),
  ('MD CITY HOSPITAL, Noida'),
  ('Magenta Clinic, Noida'),
  ('Mahanandan Super Speciality Hospital, Greater Noida'),
  ('Maheshwari Clinic, D-292, SEC-108, Noida-Greater Noida Expy, near DIVINE MEADOWS'),
  ('Mahikum Clinic, Noida Extension'),
  ('MakeO (formerly skinnsi) Skin Care Clinic, Noida Sector 18'),
  ('Manipal Hospital Ghaziabad, Noida'),
  ('Mark Hospital & Trauma Centre M/S, Noida'),
  ('Max Multi Speciality Centre, Sector 19, Noida, Noida'),
  ('Max Super Speciality Hospital, Sector 128, Noida, Noida'),
  ('Max Super Speciality Noida Hospital Parking Lot, Noida-Greater Noida Expy'),
  ('Maxplus Healthcare Clinic, Noida'),
  ('Meadows Wellness, Noida Sector 18'),
  ('Medanta Labs, Noida Sector 137'),
  ('Medanta Super Speciality Hospital, Noida'),
  ('Medcube Cloud Clinic Noida Extension, Greater Noida West'),
  ('Medicover Fertility Clinic, Noida Sector 18'),
  ('Medigo Clinic, Shop No 22, Ace Divino Commercial Market'),
  ('Medwin Hospital, Noida'),
  ('Metro Center, Noida'),
  ('Metro Hospitals & Heart Institute: Best Heart Hospital in Noida, Block X, 1, Vyapar Marg'),
  ('Metro Hospitals Multispeciality Wing, Bariatric & Metabolic Surgery Department Wing L - 94 Sector 11 Multispeciality Wing'),
  ('Metro Multispeciality Hospital, Noida'),
  ('Minocha Clinic, Noida West'),
  ('Motherhood Hospital, Noida'),
  ('Motherland Hospital, Noida'),
  ('Mount Era Clinic & Lab, First floor, Pradhan Market, opposite Trident Embassy, near Yatharth hospital'),
  ('NAVIN HOSPITAL, Noida'),
  ('NEO Hospital, Noida Sector 18'),
  ('NIMMS Hospital (You Are Family Here), Noida'),
  ('NIMMS Multi-Speciality Hospital, Greater Noida'),
  ('Nest Satya hospital, Noida'),
  ('Neuro Clinic Plus, Noida Extension'),
  ('New Look Clinic, Shop No.610, Krishna Apra Plaza, Maharaja Agrasen Marg'),
  ('Nidan clinic, A-129, Pocket 3 Block A Rd'),
  ('Niramaya clinic, Shop No-23, Kanti Devi market, A-Block'),
  ('Nix Clinic, Plot 814, behind ACE CITY'),
  ('Nix Multispeciality Hospital, Noida'),
  ('Noida Hospital, Noida'),
  ('Noida Multispeciality Hospital, M-31 Main Road Mamura, near R.K Public School'),
  ('Noida Sec-18, Captain Vijyant Thapar Marg'),
  ('Noida sector 12, Noida'),
  ('Nulife Hospital, Noida'),
  ('Numed Super Speciality Hospital, Sector 3 Rd'),
  ('OPAL CARE MULTISPECIALITY CLINIC, Shop No 29 Lower Ground Floor, Mahagun Mart, 2, 11th Ave, opp. to Greater Noida West Road'),
  ('Oasis Wave of Wellness, Noida Sector 18'),
  ('Ojas Skin Care, Noida'),
  ('Om Sai Clinic, Main Road, Kavitha Palace, Sector 62, Kavitha Palace Road'),
  ('Onyx physiocare, Noida Sector 137'),
  ('Pavi child clinic, SHOP NO 30, FIRST FLOOR, Icon Leisure valley, MARKET, Greater Noida W Rd'),
  ('Petals child clinic by Dr. Pawan Verma, Greater Noida West'),
  ('Physician Centre Dr S K Sahoo, A 123, Greater Noida W Rd'),
  ('Physiotherapy Clinic Noida Extension, Noida Extension'),
  ('Post Graduate Institute of Child Health, H8GQ+J7J PATIENT ROOM, DR BHIMRAO AMBEDKAR MULTISPECIALITY HOSPITAL, Maharaja Agrasen Marg, near Delhi Public School'),
  ('Prags Physiotherapy Clinic, Shop No -11, Ground Floor, Market City Plaza, B Block Rd, beside Globax Pharmacy, behind Fortis Hospital'),
  ('Pragya Clinic, Noida'),
  ('Prakash Hospital, Noida Sector 18'),
  ('Prasad Clinic, 299/29, Noida Sector, 18, Near Shanti Dairy, Noida Sector 18, Atta Market, Pocket E, Sector 27, Noida, Meerut Division Delhi'),
  ('Prayag Hospital & Research Centre, Noida'),
  ('PrimaCare ClearMedi Multispeciality Hospital, Noida'),
  ('Primary Health Center [PHC] Govt Hospital ,Bisrakh, Noida'),
  ('Primary Health Center-(Govt Hospital sector53, Noida'),
  ('Prisha''s Gynae & Thyroid Clinic, F-117, Sector 02, near Dauji Sweets, opposite Yatharth Hospital'),
  ('Priya Clinic, Noida'),
  ('Promhex Multispeciality Hospital In Greater Noida, Greater Noida'),
  ('QHT Hair Transplant In Noida, Noida Sector 62'),
  ('QI Spine Clinic, First Floor, Plot No - N12 and N13'),
  ('R N Hospital Pvt. Ltd., Noida'),
  ('ROBZ HOSPITAL, Noida'),
  ('RS Family Clinic, Noida West'),
  ('Rainbow Health, Market, Upper Ground Floor 06, Chamber 1, JM Florence, Greater Noida W Rd'),
  ('Rainbow Healthcare Clinic, Noida'),
  ('Rama Health Care(Rama hospital), A unit of Rama foundation, Noida'),
  ('Rama Hospital, E-2, Badal Marg'),
  ('Ravi Women''s Hospital Noida, A -1, Golf course Road'),
  ('Rk Clinic, 121, Vandana Enclave Khora Colony Sector 62 Noida, NCR'),
  ('Rohan Clinic, Noida Sector 18'),
  ('S S Clinic (Dr. Lovlesh Purshottam ), Greater Noida'),
  ('SHAKTI HEALTHCARE CLINIC, Shop No. 1, Dhan Singh Market, near A Square Mall'),
  ('SHARMA CLINIC (Dr.Vivek sharma), shop 2, Karnal market, Gali Number 3'),
  ('SHREE HOSPITAL, Noida'),
  ('SHUSHILA MULTI SPECIALITY HOSPITAL- Hospital In Gaur City, Tigri Gol Chakkar, near Greater Noida Welcome Gate'),
  ('SJM Hospital & IVF Centre, J9JR+X47 SJM Chowk'),
  ('SPES Super Speciality Hospital, Pari Chowk'),
  ('SR HOSPITAL & MATERNITY CENTRE, C-1, Buddha Bazaar road'),
  ('SS Multispeciality Hospital, Noida'),
  ('Sai Healthcare (Multi-Specialty Clinic), Shop No.10, Chauhan Market, Shahdara, opposite to Gate Number 1'),
  ('Saini Hospital , multi speciality hospital, Noida West'),
  ('Sakhiya Skin Clinic, 2nd Floor, Plot No P14, above Lenskart'),
  ('Samarpit Mediclinic, Best Gynecologist in Greater Noida West, Best Gynaecologist In Noida Extension, Noida West'),
  ('Samdosh Ayurveda Hospital, Noida'),
  ('Santosh Gynae Clinic, Noida Sector 62'),
  ('Sarvodaya Hospital, Greater Noida West (Noida Extension) – Best Superspeciality Hospital, Sarvodaya Hospital, Greater Noida W Rd'),
  ('Sexologist Dr. J Lal Clinic, Noida Sector 18'),
  ('Shanti Hospital, Noida'),
  ('Sharda Hospital, SHARDA UNIVERSITY Campus, Plot No. 32, 34'),
  ('Sharma Medicare Super Speciality Hospital and Trauma Centre, Greater Noida'),
  ('Shifa Clinic, Noida'),
  ('Shifa Skin Clinic Dr Furkan Rana, Noida Sector 62'),
  ('Shiv Clinic : Best Sexologist in Noida / India / Sex Specialist Doctor, Noida'),
  ('Shiva Clinic, Noida West'),
  ('Shivalik Hospital, A premium Mother and Child Care Hospital, Noida'),
  ('Shivalik Hospital: Best Hospital in Noida, Noida'),
  ('Shri Om Kashyap Lifeline Hospital, H95C+HQJ, Main Dadri Road, Opposite Radha Swami Satsang Vyas, near Shri ram hospital'),
  ('Shri Ram Singh (SRS) Multispeciality Hospital, Noida'),
  ('Shri ram hospital, Noida Sector 18'),
  ('Shudhhi Ayurveda Clinic & Hospital, Noida'),
  ('Singh, Tot Mall Market, Shop No.- PF-27, Block-C, 58/15A'),
  ('Skinfinity Derma, Plot No. B-1'),
  ('Smita Multispeciality Clinic, Noida Sector 137'),
  ('Society Clinic & Medicos, Greater Noida West'),
  ('Sowaka Physiocare (Dr Ritika Gaur), Noida West'),
  ('Sri Krishna Clinic, Noida'),
  ('Sudhir super speciality hospital greater Noida, Plot no 4, 1st Cross Ave, near gate no 5'),
  ('Sumitra Hospital, 119A, Jagannath Mandir Marg'),
  ('Surbhi Clinic, Noida, T-2, Amaltash Marg'),
  ('Surbhi Hospital, Golf Marg'),
  ('Surgical Intensive Care Unit (SICU) in Sector 128, Noida, Noida'),
  ('Surya Hospital-Managed By Vedansh Medicare, Noida'),
  ('Swastham Medicare Hospital, Itera, Plot No 107, opposite Fusion Homes'),
  ('THE DOCTORS CLINIC, Shop No UGF 19, Aspire plaza, GH-03, opposite of SKA Greenarch Road'),
  ('Tekram Hospital Multi Speciality Hospital Noida Sector-1, Tekram Hospital ,796,JS Roop Road, West, behind STELLAR JEEVAN'),
  ('The Auraa Care by Dr Divya Sharma, Noida Sector 62'),
  ('The Hope Clinic, Greater Noida West'),
  ('The Hope Hospital, Greater Noida'),
  ('The Women Clinic, Noida'),
  ('Titan Eye+ at Sector 18, Noida (Buy 1 Get 1 Free), Noida Sector 18'),
  ('Toothsi by MakeO, Noida Sector 18'),
  ('Truecare Clinic, Shop No. 11, UGF, Saviour GreenArch, Market, above Apollo Pharmacy'),
  ('Utkarsh Hospital Greater Noida, Noida Extension'),
  ('VCC AYURVEDA AND MEDICAL RESEARCH LLP, Authentic Kerala Ayurveda doctor/hospital in noida, slipped disc treatment near me, Noida'),
  ('Vaidya Ji ayurvedic clinic, Noida West'),
  ('Vashishth Clinic, 58/6, C, Block 58/6, Sector 62 Rd'),
  ('Vet Land Pet Clinic & Surgery Centre, Noida Sector 137'),
  ('Vinayak Hospital, Noida Sector 18'),
  ('Virtue Health Clinic, LG-22, La Galleria Market, Greater Noida West'),
  ('Vision Plus Eye Centre, FF & SF Kisan Tower Capt Shashikant sharma Marg, 215, near Jagannath Mandir Marg, opp. Metro Pillar No'),
  ('Vrandavan Hospital, Noida'),
  ('WE CARE CLINIC, 2 market, A- 002, ground floor'),
  ('We Skin Clinic, Shop no 10 First floor, mother dairy, the City plaza, Market'),
  ('WeCare Pathlab~Full Body chekup Noida, Noida Sector 137'),
  ('Well Care Hospital, Nala road, near Metro Station Noida Sector 101'),
  ('WellCare Family Clinic and Pharmacy, Greater Noida'),
  ('Winsome Hair Clinic, Noida Sector 18'),
  ('Xpert Medicare Clinics , Gynecologist & Obstetrician, Noida'),
  ('YASH POLYCLINIC, opposite Block B'),
  ('YAVAN CLINIC n GYNAE CENTRE EMERGENCY TRAUMA, 937,budh bazar 33 FEETA ROAD LOKPRIYA VIHAR KHORA GZB, Khora Rd'),
  ('Yamuna Dental Clinic, Deepak Vihar Khoda Colony Rd, near purana kalka store and Goyal saree house'),
  ('Yashoda Super Speciality Hospital, Noida Sector 62'),
  ('Yatharth Super Speciality Hospital Noida Extension, Noida'),
  ('Yatharth Super Speciality Hospital, Greater Noida, Plot No 32'),
  ('Yatharth Super Speciality Hospital, Plot No. 1'),
  ('𝗗𝗿 𝗞𝗨𝗠𝗔𝗥''𝗦 𝗙𝗔𝗠𝗜𝗟𝗬 𝗖𝗟𝗜𝗡𝗜𝗖 𝗮𝗻𝗱 𝗩𝗔𝗖𝗖𝗜𝗡𝗔𝗧𝗜𝗢𝗡 𝗖𝗘𝗡𝗧𝗥𝗘 DR RANJAN KUMAR, Noida')
ON CONFLICT (label) DO NOTHING;
