-- SUPERSEDED — do not run this file.
--
-- It had no number, so it never ran in sequence and the live project ended up
-- without contact_messages or ops_metrics at all: /support failed with PGRST205
-- on every message sent, and the live-operations widget read nothing.
--
-- The contents now live in 28_CONTACT_AND_METRICS.sql, plus length constraints
-- on the anonymously-insertable contact form and user_id/handled_at columns.
-- Run that instead.
